version: '3.1'
services:
  db:
    image: mysql
    container_name: pnbdb
    ports:
      - "3306:3306"
    environment:
      - DB_NAME=pnb
      - DB_USER=root
      - DB_PASS=password
      - MYSQL_ROOT_PASSWORD=
  api:
    build: ./
    container_name: pnbapi
    ports:
      - "3001:3001"
    depends_on:
      - db
  front:
    build: ./../pnb_front/
    container_name: pnbfront
    ports:
      - "8010:8010"
    depends_on:
      - api
