version: '3.8'
services:
  db:
    image: mysql
    container_name: pnbdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pnb
  api:
    build: ./
    container_name: pnbapi
    restart: on-failure
    command: bash -c "npm run knex && npm run seeds && npm run start"
    ports:
      - "3001:3001"
    depends_on:
      - db
  front:
    build: ./../pnb_front/
    container_name: pnbfront
    ports:
      - "8010:8010"
    depends_on:
      - api
